In [8]:
import numpy as np


In [ ]:
#creat numpyarray
arr = np.array([1, 2, 3, 4, 5])
print("Numpy Array:", type(arr))
arr2 =np.array([1, 2, 3, 4, 5,'hello'])
print("Numpy Array with mixed types:", type(arr2), arr2.dtype)

#creating 2d aray
#data should be homogenious
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Numpy Array:", arr_2d.shape)
print("2D Numpy Array Dimensions:", arr_2d)

Numpy Array: <class 'numpy.ndarray'>
Numpy Array with mixed types: <class 'numpy.ndarray'> <U21
2D Numpy Array: (3, 3)
2D Numpy Array Dimensions: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
arr1 =np.zeros((3,4), dtype="int64")
print("Array of Zeros:\n", arr1)

Array of Zeros:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [13]:
text_array =arr.astype('str')
print("Array converted to string type:", text_array, text_array.dtype)
print(arr, arr.dtype)

Array converted to string type: ['1' '2' '3' '4' '5'] <U21
[1 2 3 4 5] int64
