In [12]:
import numpy as np


In [13]:
#creat numpyarray
arr = np.array([1, 2, 3, 4, 5])
print("Numpy Array:", type(arr))
arr2 =np.array([1, 2, 3, 4, 5,'hello'])
print("Numpy Array with mixed types:", type(arr2), arr2.dtype)

#creating 2d aray
#data should be homogenious
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Numpy Array:", arr_2d.shape)
print("2D Numpy Array Dimensions:", arr_2d)

Numpy Array: <class 'numpy.ndarray'>
Numpy Array with mixed types: <class 'numpy.ndarray'> <U21
2D Numpy Array: (3, 3)
2D Numpy Array Dimensions: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
arr1 =np.zeros((3,4), dtype="int64")
print("Array of Zeros:\n", arr1)

Array of Zeros:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [15]:
text_array =arr.astype('str')
print("Array converted to string type:", text_array, text_array.dtype)
print(arr, arr.dtype)

Array converted to string type: ['1' '2' '3' '4' '5'] <U21
[1 2 3 4 5] int64


In [16]:
#  numpy array and basics
python_list =[1,2,3,4]
print("python list",python_list*2)
numpy_array = np.array(python_list)
print("numpy array",numpy_array*2)

import time
start = time.time()
python_list = [i*2 for i in range(1000000)]
end = time.time()
print("Time taken by Python list:", end - start)

start = time.time()
numpy_array = np.array(python_list)
end = time.time()
print("Time taken by NumPy array:", end - start)

python list [1, 2, 3, 4, 1, 2, 3, 4]
numpy array [2 4 6 8]
Time taken by Python list: 0.029219627380371094
Time taken by NumPy array: 0.029175996780395508


In [17]:
#creating array from scratch
arr_zeros = np.zeros((2,3))
print("Array of Zeros:\n", arr_zeros)

arr_ones = np.ones((2,3))
print("Array of Ones:\n", arr_ones)
#full
arr_full = np.full((2,3), 7)
print("Array filled with 7:\n", arr_full)
#random
arr_random =np.random.rand(2,3)
print("Array of random numbers between 0 and 1:\n", arr_random)
#arange
arr_arange = np.arange(0, 10, 2)
print("Array created using arange (0 to 10 with step 2):\n", arr_arange)

Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Array filled with 7:
 [[7 7 7]
 [7 7 7]]
Array of random numbers between 0 and 1:
 [[0.54055991 0.60217276 0.31213351]
 [0.64553529 0.896629   0.28956078]]
Array created using arange (0 to 10 with step 2):
 [0 2 4 6 8]


In [19]:
arr = np.arange(12)
print("Original Array:", arr)
reshaped_arr = arr.reshape(3, 4)
print("Reshaped Array (3x4):\n", reshaped_arr)
rvaled_arr = arr.reshape(-1, 4)
print("Reshaped Array with inferred rows (-1):\n", rvaled_arr)

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped Array with inferred rows (-1):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
